# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_environment.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 950)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(9, -1, 1481, 901))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.optimize_btn = QtWidgets.QPushButton(self.page)
        self.optimize_btn.setGeometry(QtCore.QRect(680, 420, 75, 23))
        self.optimize_btn.setObjectName("optimize_btn")
        self.obj_detection_radio_btn = QtWidgets.QRadioButton(self.page)
        self.obj_detection_radio_btn.setGeometry(QtCore.QRect(460, 90, 111, 17))
        self.obj_detection_radio_btn.setObjectName("obj_detection_radio_btn")
        self.placeholder_radio_btn = QtWidgets.QRadioButton(self.page)
        self.placeholder_radio_btn.setGeometry(QtCore.QRect(820, 90, 82, 17))
        self.placeholder_radio_btn.setObjectName("placeholder_radio_btn")
        self.browse_btn = QtWidgets.QPushButton(self.page)
        self.browse_btn.setGeometry(QtCore.QRect(920, 260, 75, 23))
        self.browse_btn.setObjectName("browse_btn")
        self.dataset_path_textbox = QtWidgets.QTextEdit(self.page)
        self.dataset_path_textbox.setGeometry(QtCore.QRect(590, 250, 281, 31))
        self.dataset_path_textbox.setObjectName("dataset_path_textbox")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.img_step_label = QtWidgets.QLabel(self.page_2)
        self.img_step_label.setGeometry(QtCore.QRect(890, 50, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.img_step_label.setFont(font)
        self.img_step_label.setObjectName("img_step_label")
        self.img_step_slider = QtWidgets.QSlider(self.page_2)
        self.img_step_slider.setGeometry(QtCore.QRect(680, 50, 160, 22))
        self.img_step_slider.setMinimum(1)
        self.img_step_slider.setMaximum(100)
        self.img_step_slider.setOrientation(QtCore.Qt.Horizontal)
        self.img_step_slider.setObjectName("img_step_slider")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(536, 50, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.nr_epochs_slider = QtWidgets.QSlider(self.page_2)
        self.nr_epochs_slider.setGeometry(QtCore.QRect(680, 120, 160, 22))
        self.nr_epochs_slider.setMinimum(1)
        self.nr_epochs_slider.setMaximum(10000)
        self.nr_epochs_slider.setSingleStep(60)
        self.nr_epochs_slider.setPageStep(10)
        self.nr_epochs_slider.setOrientation(QtCore.Qt.Horizontal)
        self.nr_epochs_slider.setObjectName("nr_epochs_slider")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(530, 120, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.nr_of_epochs_label = QtWidgets.QLabel(self.page_2)
        self.nr_of_epochs_label.setGeometry(QtCore.QRect(890, 120, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nr_of_epochs_label.setFont(font)
        self.nr_of_epochs_label.setObjectName("nr_of_epochs_label")
        self.generate_btn = QtWidgets.QPushButton(self.page_2)
        self.generate_btn.setGeometry(QtCore.QRect(720, 190, 75, 23))
        self.generate_btn.setObjectName("generate_btn")
        self.plot_canvas = QtWidgets.QLabel(self.page_2)
        self.plot_canvas.setGeometry(QtCore.QRect(166, 242, 1181, 611))
        self.plot_canvas.setText("")
        self.plot_canvas.setObjectName("plot_canvas")
        self.back_btn = QtWidgets.QPushButton(self.page_2)
        self.back_btn.setGeometry(QtCore.QRect(1390, 870, 75, 23))
        self.back_btn.setObjectName("back_btn")
        self.download_btn = QtWidgets.QPushButton(self.page_2)
        self.download_btn.setGeometry(QtCore.QRect(10, 870, 111, 23))
        self.download_btn.setObjectName("download_btn")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.img_step_slider.valueChanged['int'].connect(self.img_step_label.setNum)
        self.nr_epochs_slider.valueChanged['int'].connect(self.nr_of_epochs_label.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.optimize_btn.setText(_translate("MainWindow", "Optimize"))
        self.obj_detection_radio_btn.setText(_translate("MainWindow", "Object Detection"))
        self.placeholder_radio_btn.setText(_translate("MainWindow", "Placeholder"))
        self.browse_btn.setText(_translate("MainWindow", "Browse"))
        self.img_step_label.setText(_translate("MainWindow", "1"))
        self.label.setText(_translate("MainWindow", "Image Step:"))
        self.label_2.setText(_translate("MainWindow", "Nr of epochs:"))
        self.nr_of_epochs_label.setText(_translate("MainWindow", "1"))
        self.generate_btn.setText(_translate("MainWindow", "Generate"))
        self.back_btn.setText(_translate("MainWindow", "Back"))
        self.download_btn.setText(_translate("MainWindow", "Download Models"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
